# Generated by Django 5.0.3 on 2024-04-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_tag_question_tags_question_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerlike',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='score',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_img',
            field=models.ImageField(default='static/img/avatar.png', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='status',
            field=models.CharField(choices=[(-1, 'Disliked'), (1, 'Liked')], max_length=1),
        ),
    ]
