# Generated by Django 5.0.3 on 2024-04-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_answer_score_question_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='answers_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='questions_counter',
            field=models.IntegerField(default=0),
        ),
    ]
