# Generated by Django 5.0.3 on 2024-04-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_profile_avatar_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_img',
            field=models.ImageField(blank=True, default='img/avatar.png', null=True, upload_to='uploads/'),
        ),
    ]
