# Generated by Django 5.0.3 on 2024-04-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_question_answers_counter_alter_profile_avatar_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='questions_counter',
            field=models.IntegerField(default=0),
        ),
    ]
