# Generated by Django 5.0.3 on 2024-04-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_answerlike_author_alter_questionlike_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerlike',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Disliked'), (1, 'Liked')]),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Disliked'), (1, 'Liked')]),
        ),
    ]
