# Generated by Django 5.0.4 on 2024-05-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_profile_avatar_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
