# Generated by Django 5.0.4 on 2024-05-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_profile_avatar_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar_img',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
